//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanRuou
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDonNhap
    {
        public string sohdn { get; set; }
        public string mahang { get; set; }
        public int soluong { get; set; }
        public double dongia { get; set; }
        public double giamgia { get; set; }
        public double thanhtien { get; set; }
    
        public virtual DMHangHoa DMHangHoa { get; set; }
        public virtual HoaDonNhap HoaDonNhap { get; set; }
    }
}
