//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanRuou
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMHangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMHangHoa()
        {
            this.ChiTietHoaDonBans = new HashSet<ChiTietHoaDonBan>();
            this.ChiTietHoaDonNhaps = new HashSet<ChiTietHoaDonNhap>();
        }
    
        public string mahang { get; set; }
        public string tenhang { get; set; }
        public string maloai { get; set; }
        public string madungluong { get; set; }
        public string macongdung { get; set; }
        public string machatlieu { get; set; }
        public string mahinhdang { get; set; }
        public string mado { get; set; }
        public string mamau { get; set; }
        public string manuocsx { get; set; }
        public int soluong { get; set; }
        public double dongianhap { get; set; }
        public double dongiaban { get; set; }
        public string thoigianbaohanh { get; set; }
        public string ghichu { get; set; }
    
        public virtual ChatLieu ChatLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonBan> ChiTietHoaDonBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonNhap> ChiTietHoaDonNhaps { get; set; }
        public virtual CongDung CongDung { get; set; }
        public virtual DoRuou DoRuou { get; set; }
        public virtual DungLuong DungLuong { get; set; }
        public virtual HinhDang HinhDang { get; set; }
        public virtual Loai Loai { get; set; }
        public virtual MauSac MauSac { get; set; }
        public virtual NuocSanXuat NuocSanXuat { get; set; }
    }
}
