//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanRuou
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLBREntities : DbContext
    {
        public QLBREntities()
            : base("name=QLBREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatLieu> ChatLieux { get; set; }
        public virtual DbSet<ChiTietHoaDonBan> ChiTietHoaDonBans { get; set; }
        public virtual DbSet<ChiTietHoaDonNhap> ChiTietHoaDonNhaps { get; set; }
        public virtual DbSet<CongDung> CongDungs { get; set; }
        public virtual DbSet<CongViec> CongViecs { get; set; }
        public virtual DbSet<DMHangHoa> DMHangHoas { get; set; }
        public virtual DbSet<DoRuou> DoRuous { get; set; }
        public virtual DbSet<DungLuong> DungLuongs { get; set; }
        public virtual DbSet<HinhDang> HinhDangs { get; set; }
        public virtual DbSet<HoaDonBan> HoaDonBans { get; set; }
        public virtual DbSet<HoaDonNhap> HoaDonNhaps { get; set; }
        public virtual DbSet<Khachhang> Khachhangs { get; set; }
        public virtual DbSet<Loai> Loais { get; set; }
        public virtual DbSet<MauSac> MauSacs { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NuocSanXuat> NuocSanXuats { get; set; }
    
        public virtual int updateHDBAN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateHDBAN");
        }
    
        public virtual int ThemHDB(string sohdb, string manhanvien, Nullable<System.DateTime> ngayban, string makhach, Nullable<double> tongtien, string mahang, Nullable<int> soluong, Nullable<double> dongia, Nullable<double> giamgia, Nullable<double> thanhtien)
        {
            var sohdbParameter = sohdb != null ?
                new ObjectParameter("sohdb", sohdb) :
                new ObjectParameter("sohdb", typeof(string));
    
            var manhanvienParameter = manhanvien != null ?
                new ObjectParameter("manhanvien", manhanvien) :
                new ObjectParameter("manhanvien", typeof(string));
    
            var ngaybanParameter = ngayban.HasValue ?
                new ObjectParameter("ngayban", ngayban) :
                new ObjectParameter("ngayban", typeof(System.DateTime));
    
            var makhachParameter = makhach != null ?
                new ObjectParameter("makhach", makhach) :
                new ObjectParameter("makhach", typeof(string));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(double));
    
            var mahangParameter = mahang != null ?
                new ObjectParameter("mahang", mahang) :
                new ObjectParameter("mahang", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(double));
    
            var giamgiaParameter = giamgia.HasValue ?
                new ObjectParameter("giamgia", giamgia) :
                new ObjectParameter("giamgia", typeof(double));
    
            var thanhtienParameter = thanhtien.HasValue ?
                new ObjectParameter("thanhtien", thanhtien) :
                new ObjectParameter("thanhtien", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemHDB", sohdbParameter, manhanvienParameter, ngaybanParameter, makhachParameter, tongtienParameter, mahangParameter, soluongParameter, dongiaParameter, giamgiaParameter, thanhtienParameter);
        }
    
        public virtual ObjectResult<Cau6_Result> Cau6(string maKH)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cau6_Result>("Cau6", maKHParameter);
        }
    
        public virtual ObjectResult<Cau9_Result> Cau9(string maHang)
        {
            var maHangParameter = maHang != null ?
                new ObjectParameter("maHang", maHang) :
                new ObjectParameter("maHang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cau9_Result>("Cau9", maHangParameter);
        }
    
        public virtual ObjectResult<Cau8_Result> Cau8(string nam)
        {
            var namParameter = nam != null ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cau8_Result>("Cau8", namParameter);
        }
    }
}
